### ISSUE TITLE
Implement scripts for installing repos curlbash style

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs-legacy#501]
As we attempt to document the installation of packages built using sensu-omnibus, the explosion of build permutations makes a good argument for providing curlbash scripts similar to https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh for automating the detection of OS versions, architectures, etc.

**Comment by mbbroberg** [comment]
I'm not positive if this was resolved, still needed, should be dropped or kept. Please close or clone when you get a sec @cwjohnston @asachs01 or @Blue0ctober

**Comment by mbbroberg** [comment]
Calling this done. Please reopen on the new site if I was wrong! 👋
