### ISSUE TITLE
DISCUSS: This project is difficult to use independently of the private website project

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs-legacy#543]
Currently the content of this repo is pulled into the Sensu website as part of publishing that site from it's private repo. This makes it painful to preview changes for those who have access to the private website repo, and practically impossible for those who don't.

In the interest of solving this problem and improving our documentation overall, I think we should establish criteria for selecting a different tool/method to generate online documentation.

Requirements
- [ ] Supports writing docs in markdown
- [ ] Generates static site we can host in S3 or similar
- [ ] Local development/preview possible without access to existing private website project
- [ ] Online search

Nice to have
- [ ] Sidebar examples à la [Stripe API Docs](https://stripe.com/docs/api)

**Comment by cwjohnston** [comment]
I think http://www.mkdocs.org/ looks promising

**Comment by calebhailey** [comment]
For posterity, I believe the tools that have discussed wanting to look at internally (within Sensu, Inc.) are: 

- http://www.mkdocs.org/ 
- https://readthedocs.org/ 
- http://readme.io/ (hosted only)

This isn't to say these are the only options, they're just the ones we've looked at so far. Ideally I would like to see us end up with a fully self-contained documentation website that can be hosted at https://docs.sensuapp.org (for example), and that can be contributed to by cloning this repository and running a local instance of the same website in some kind of development mode.

**Comment by portertech** [comment]
We think a good "quick test" is to create a new project/repository, using mkdocs, and port a very specific part of the current Sensu documentation to get an idea of the level of pain.

**Comment by cwjohnston** [comment]
We've ported the bulk of content from the 0.29 documentation in this repo to a new project usng mkdocs: https://github.com/sensu/sensu-mkdocs/ 

Live preview here: https://sensu.github.io/sensu-mkdocs/

Once we've sorted out formatting issues described in https://github.com/sensu/sensu-mkdocs/issues/6 I think we'll be ready to publish this new iteration at docs.sensuapp.org. 👍

**Comment by majormoses** [comment]
something that should be considered with the go forward solution: https://github.com/sensu/sensu-docs/issues/680

**Comment by cwjohnston** [comment]
Since my last comment in April we've determined that the mkdocs project isn't a good fit for us, in part because it lacks support for maintaining multiple versions of product documentation. As a result we've begun an effort to migrate our documentation to sensu/sensu-docs-site, a Hugo powered site which will be published independently of the existing sensuapp.org website.

**Comment by mbbroberg** [comment]
All of your dreams have come true: https://github.com/sensu/sensu-docs-site/

![tenor 28](https://user-images.githubusercontent.com/1744971/37721858-d55d3be8-2ce7-11e8-9bc8-226fc3329087.gif)
