### ISSUE TITLE
Add template example for enterprise slack handler

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs-legacy#688]
While templating is supported, it might be a better UX for us to create a template so that those unfamiliar with erb templates might have something to go off of.

**Comment by majormoses** [comment]
interesting, I heard from a community member templating was not possible with the enterprise handler and they were using the community one for this reason.

**Comment by mbbroberg** [comment]
That appears to be a misconception. 👍 to clarifying it @asachs01!

**Comment by mbbroberg** [comment]
That appears to be a misconception. 👍 to clarifying it @asachs01!

**Comment by mbbroberg** [comment]
@asachs01 could you clone this issue over if it isn't addressed already in https://github.com/sensu/sensu-docs-site/? Thanks!

**Comment by mbbroberg** [comment]
Please reopen on the other project if we still need this.
