### ISSUE TITLE
This repository should be deprecated as the site of new documentation changes

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs-legacy#690]
As noted in https://github.com/sensu/sensu-docs/issues/543#issuecomment-358744641 we are moving forward with a new Hugo powered documentation site. The README and CONTRIBUTING docs for this project should be updated to help folks find the new project.

**Comment by mbbroberg** [comment]
Starting a branch to handle the deprecation notice. In addition, I'd like to recommend we do some GitHub-fu: 

- rename this repository to `sensu-docs-legacy`
- rename `sensu-docs-site` to `sensu-docs` 

By doing so, we get the advantage of both https://github.com/sensu/sensu-docs & https://github.com/sensu/sensu-docs-site directing users to our latest documentation (which will have a brief notice about finding legacy documentation). 

If you agree @cwjohnston I'll consider that in scope of closing this issue.

**Comment by mbbroberg** [comment]
Told to give this a whirl. Hold my beer 🍺

**Comment by mbbroberg** [comment]
Hmm, doesn't look like I can be as sneaky as I intended here. Renamed this one to legacy, but it keeps a hold of the original name as well from the looks of it: 

<img width="433" alt="screen shot 2018-03-20 at 4 12 20 pm" src="https://user-images.githubusercontent.com/1744971/37687646-99765620-2c59-11e8-97ab-4068df17cc15.png">

**Comment by cwjohnston** [comment]
![](https://media3.giphy.com/media/8UF0EXzsc0Ckg/200.gif)
